name : Destroy Azure Resources

on:
  workflow_dispatch:
  
 #remove# pull_request:
 #remove#   types: [labeled]

env:
  AZURE_RESOURCE_GROUP: cd-with-actions

jobs:
    destroy-azure-resources:
      runs-on: ubuntu-latest

#removed manual run# if: contains(github.event.pull_request.labels.*.name, 'destroy environment') 

      steps :
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}

        - name: Desotry Azure environment
          if: success()
          run:
            az group delete --name ${{env.AZURE_RESOURCE_GROUP}}  --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --yes
